### ISSUE TITLE
Add library('objectStoreR') in the wiki page/instructions

### ISSUE THREAD

**Issue by chetnawarade** [IBMDataScience/objectStoreR#1]
Please add this to the doc as I worked around this, but one of my co-workers got caught up with error:

Error in eval(expr, envir, enclos): could not find function "objectStore.get"

**Comment by charles2588** [comment]
Adding comment to get this ASAP as users are reporting it.
You have to install 
install.packages('devtools')
library(devtools)
install_github('IBMDataScience/objectStoreR')

and then run library to load objectStoreR to actually load the package
library('objectStoreR')

then use objectStore.get

**Comment by gfilla** [comment]
Thanks @charles2588 !  Updated the readme docs.
